/**
 * householdsService.js
 *
 * FIX: fetchHouseholdById used `.single()` which throws HTTP 406 when no row
 * is found (deleted household, stale ID in URL). Changed to `.maybeSingle()`
 * so callers receive null and can show a proper "Not found" state.
 */
import { supabase } from '../core/supabase';

const LIST_COLUMNS = `
  id, household_no, purok_id, house_no, street, barangay, city, province,
  ownership_type, structure_type, remarks,
  is_active, is_archived,
  created_at, updated_at,
  puroks_tbl ( id, name )
`;

const MEMBERS_COLUMNS = `
  id, household_id, resident_id, role, is_head, joined_at,
  residents_tbl ( id, first_name, middle_name, last_name, suffix, gender, contact_number )
`;

// ── Households ─────────────────────────────────────────────────────────────────

/**
 * Fetch all active, non-archived households.
 */
export async function fetchHouseholds() {
  const { data, error } = await supabase
    .from('households_tbl')
    .select(LIST_COLUMNS)
    .eq('is_archived', false)
    .order('household_no', { ascending: true });

  if (error) throw error;
  return data ?? [];
}

/**
 * Fetch a single household with its members.
 *
 * FIX: Changed household lookup from `.single()` to `.maybeSingle()`.
 * `.single()` throws HTTP 406 when the row doesn't exist. `.maybeSingle()`
 * returns null safely — callers should check for null and show "not found".
 *
 * @returns {{ ...household, members: [] } | null}
 */
export async function fetchHouseholdById(id) {
  const [householdResult, membersResult] = await Promise.all([
    supabase
      .from('households_tbl')
      .select(LIST_COLUMNS)
      .eq('id', id)
      .maybeSingle(), // FIX: was .single() — throws 406 if row not found
    supabase
      .from('household_members_tbl')
      .select(MEMBERS_COLUMNS)
      .eq('household_id', id)
      .order('is_head', { ascending: false }),
  ]);

  if (householdResult.error) throw householdResult.error;
  if (membersResult.error) throw membersResult.error;

  if (!householdResult.data) return null; // household not found

  return {
    ...householdResult.data,
    members: membersResult.data ?? [],
  };
}

/**
 * Create a new household.
 * household_no is auto-generated by DB trigger if omitted.
 */
export async function createHousehold(formData, actorUserId) {
  const payload = buildHouseholdPayload(formData);
  payload.created_by = actorUserId ?? null;
  payload.updated_by = actorUserId ?? null;

  const { data, error } = await supabase
    .from('households_tbl')
    .insert(payload)
    .select('id, household_no')
    .single();

  if (error) throw error;

  // Insert members if provided
  if (formData.members?.length) {
    await upsertMembers(data.id, formData.members);
  }

  return data;
}

/**
 * Update an existing household.
 */
export async function updateHousehold(id, formData, actorUserId) {
  const payload = buildHouseholdPayload(formData);
  payload.updated_by = actorUserId ?? null;
  // Note: updated_at is also handled by the DB trigger (trg_set_updated_at),
  // but setting it explicitly here ensures immediate consistency.
  payload.updated_at = new Date().toISOString();

  const { data, error } = await supabase
    .from('households_tbl')
    .update(payload)
    .eq('id', id)
    .select('id, household_no')
    .single();

  if (error) throw error;

  // Replace members if provided
  if (formData.members !== undefined) {
    await supabase
      .from('household_members_tbl')
      .delete()
      .eq('household_id', id);

    if (formData.members.length) {
      await upsertMembers(id, formData.members);
    }
  }

  return data;
}

/**
 * Soft-archive a household.
 */
export async function archiveHousehold(id, actorUserId) {
  const { error } = await supabase
    .from('households_tbl')
    .update({
      is_archived: true,
      is_active: false,
      archived_at: new Date().toISOString(),
      archived_by: actorUserId ?? null,
      updated_at: new Date().toISOString(),
    })
    .eq('id', id);

  if (error) throw error;
}

/**
 * Hard-delete a household (cascades to household_members_tbl).
 */
export async function deleteHousehold(id) {
  const { error } = await supabase
    .from('households_tbl')
    .delete()
    .eq('id', id);

  if (error) throw error;
}

// ── Household Members ──────────────────────────────────────────────────────────

/**
 * Fetch members of a household.
 */
export async function fetchHouseholdMembers(householdId) {
  const { data, error } = await supabase
    .from('household_members_tbl')
    .select(MEMBERS_COLUMNS)
    .eq('household_id', householdId)
    .order('is_head', { ascending: false });

  if (error) throw error;
  return data ?? [];
}

/**
 * Add a resident to a household.
 */
export async function addHouseholdMember(householdId, residentId, role = 'Other', isHead = false) {
  const { error } = await supabase
    .from('household_members_tbl')
    .upsert({
      household_id: householdId,
      resident_id: residentId,
      role,
      is_head: isHead,
    }, { onConflict: 'household_id,resident_id' });

  if (error) throw error;
}

/**
 * Remove a resident from a household.
 */
export async function removeHouseholdMember(householdId, residentId) {
  const { error } = await supabase
    .from('household_members_tbl')
    .delete()
    .eq('household_id', householdId)
    .eq('resident_id', residentId);

  if (error) throw error;
}

// ── Puroks ─────────────────────────────────────────────────────────────────────

/**
 * Fetch all active puroks for dropdowns.
 */
export async function fetchPuroks() {
  const { data, error } = await supabase
    .from('puroks_tbl')
    .select('id, name, description')
    .eq('is_active', true)
    .order('name', { ascending: true });

  if (error) throw error;
  return data ?? [];
}

// ── Helpers ────────────────────────────────────────────────────────────────────

function buildHouseholdPayload(d) {
  return {
    purok_id: d.purokId || null,
    house_no: d.houseNo?.trim() || null,
    street: d.street?.trim() || null,
    barangay: d.barangay?.trim() || 'San Bartolome',
    city: d.city?.trim() || 'Quezon City',
    province: d.province?.trim() || 'Metro Manila',
    zip_code: d.zipCode?.trim() || null,
    ownership_type: d.ownershipType?.trim() || null,
    structure_type: d.structureType?.trim() || null,
    remarks: d.remarks?.trim() || null,
    is_active: d.isActive ?? true,
  };
}

async function upsertMembers(householdId, members) {
  const rows = members.map((m) => ({
    household_id: householdId,
    resident_id: m.residentId,
    role: m.role || 'Other',
    is_head: m.isHead ?? false,
    joined_at: m.joinedAt || null,
  }));

  const { error } = await supabase
    .from('household_members_tbl')
    .insert(rows);

  if (error) throw error;
}