/**
 * residentsService.js
 *
 * FIX: fetchResidentById used `.single()` which throws HTTP 406 when no row
 * is found (e.g. deleted record, stale ID in URL). Changed to `.maybeSingle()`
 * so callers receive `null` and can show a proper "Not found" state instead of
 * crashing with an unhandled error.
 *
 * All other service functions were already correct.
 */
import { supabase } from '../core/supabase';

// ── Column sets ────────────────────────────────────────────────────────────────
const LIST_COLUMNS = `
  id, resident_no, first_name, middle_name, last_name, suffix,
  gender, birthdate, contact_number, email, status, is_archived,
  house_no, street, barangay, city, purok_id, household_id,
  created_at, updated_at
`;

const DETAIL_COLUMNS = `
  id, resident_no,
  first_name, middle_name, last_name, suffix,
  gender, birthdate, birthplace, civil_status, nationality, religion,
  occupation, monthly_income,
  is_voter, voter_id_no,
  is_pwd, pwd_id_no,
  is_solo_parent, is_4ps_beneficiary, is_senior_citizen,
  educational_attainment, blood_type, photo_url,
  contact_number, email,
  household_id, purok_id, house_no, street, barangay, city, province, zip_code,
  years_of_residency, is_renter,
  philsys_id_no, sss_no, tin_no, philhealth_no, pagibig_no,
  passport_no, drivers_license_no, postal_id_no,
  emergency_contact_name, emergency_contact_relationship, emergency_contact_number,
  qr_code, status, is_archived, archived_at,
  created_at, updated_at
`;

// ── Read ───────────────────────────────────────────────────────────────────────

/**
 * Fetch all non-archived residents.
 * Returns array sorted by last_name ASC.
 */
export async function fetchResidents() {
  const { data, error } = await supabase
    .from('residents_tbl')
    .select(LIST_COLUMNS)
    .eq('is_archived', false)
    .order('last_name', { ascending: true });

  if (error) throw error;
  return data ?? [];
}

/**
 * Fetch a single resident by id (full detail).
 *
 * FIX: Changed from `.single()` to `.maybeSingle()`.
 * `.single()` throws HTTP 406 when the row doesn't exist (deleted record,
 * stale navigation, bad ID in URL). `.maybeSingle()` returns null instead,
 * allowing callers to show a user-friendly "not found" message.
 *
 * @returns {object|null} Resident record or null if not found
 */
export async function fetchResidentById(id) {
  const { data, error } = await supabase
    .from('residents_tbl')
    .select(DETAIL_COLUMNS)
    .eq('id', id)
    .maybeSingle(); // FIX: was .single() — throws 406 if row not found

  if (error) throw error;
  return data; // null if not found — callers must handle this
}

/**
 * Lookup a resident by their unique qr_code value.
 * Used by the Verification page.
 */
export async function fetchResidentByQrCode(qrCode) {
  const { data, error } = await supabase
    .from('residents_tbl')
    .select(DETAIL_COLUMNS)
    .eq('qr_code', qrCode)
    .eq('is_archived', false)
    .maybeSingle();

  if (error) throw error;
  return data; // null if not found
}

// ── Write ──────────────────────────────────────────────────────────────────────

/**
 * Insert a new resident.
 * resident_no is auto-generated by DB trigger if omitted.
 * qr_code is auto-generated by DB trigger.
 */
export async function createResident(formData, actorUserId) {
  const payload = buildPayload(formData);
  payload.created_by = actorUserId ?? null;
  payload.updated_by = actorUserId ?? null;

  const { data, error } = await supabase
    .from('residents_tbl')
    .insert(payload)
    .select('id, resident_no')
    .single();

  if (error) throw error;
  return data;
}

/**
 * Update an existing resident.
 */
export async function updateResident(id, formData, actorUserId) {
  const payload = buildPayload(formData);
  payload.updated_by = actorUserId ?? null;
  payload.updated_at = new Date().toISOString();

  const { data, error } = await supabase
    .from('residents_tbl')
    .update(payload)
    .eq('id', id)
    .select('id, resident_no')
    .single();

  if (error) throw error;
  return data;
}

/**
 * Soft-archive a resident (sets is_archived=true, status='Inactive').
 */
export async function archiveResident(id, actorUserId) {
  const { error } = await supabase
    .from('residents_tbl')
    .update({
      is_archived: true,
      archived_at: new Date().toISOString(),
      archived_by: actorUserId ?? null,
      status: 'Inactive',
      updated_at: new Date().toISOString(),
    })
    .eq('id', id);

  if (error) throw error;
}

/**
 * Hard-delete a resident (use only when fully intended).
 * RLS enforces admin-only; front-end should still confirm.
 */
export async function deleteResident(id) {
  const { error } = await supabase
    .from('residents_tbl')
    .delete()
    .eq('id', id);

  if (error) throw error;
}

// ── Helpers ────────────────────────────────────────────────────────────────────

/**
 * Maps form field names to exact DB column names.
 * Prevents mass-assignment of unknown columns.
 */
function buildPayload(d) {
  return {
    // Personal
    first_name: d.firstName?.trim() || null,
    middle_name: d.middleName?.trim() || null,
    last_name: d.lastName?.trim() || null,
    suffix: d.suffix?.trim() || null,
    gender: d.gender || null,
    birthdate: d.birthdate || null,
    birthplace: d.birthplace?.trim() || null,
    civil_status: d.civilStatus || null,
    nationality: d.nationality?.trim() || 'Filipino',
    religion: d.religion?.trim() || null,
    occupation: d.occupation?.trim() || null,
    monthly_income: d.monthlyIncome ? parseFloat(d.monthlyIncome) : null,
    // Flags
    is_voter: d.isVoter ?? false,
    voter_id_no: d.voterIdNo?.trim() || null,
    is_pwd: d.isPwd ?? false,
    pwd_id_no: d.pwdIdNo?.trim() || null,
    is_solo_parent: d.isSoloParent ?? false,
    is_4ps_beneficiary: d.is4psBeneficiary ?? false,
    is_senior_citizen: d.isSeniorCitizen ?? false,
    educational_attainment: d.educationalAttainment?.trim() || null,
    blood_type: d.bloodType?.trim() || null,
    photo_url: d.photoUrl || null,
    // Contact
    contact_number: d.contactNumber?.trim() || null,
    email: d.email?.trim() || null,
    // Address
    household_id: d.householdId || null,
    purok_id: d.purokId || null,
    house_no: d.houseNo?.trim() || null,
    street: d.street?.trim() || null,
    barangay: d.barangay?.trim() || 'San Bartolome',
    city: d.city?.trim() || 'Quezon City',
    province: d.province?.trim() || 'Metro Manila',
    zip_code: d.zipCode?.trim() || null,
    years_of_residency: d.yearsOfResidency ? parseInt(d.yearsOfResidency, 10) : null,
    is_renter: d.isRenter ?? false,
    // IDs
    philsys_id_no: d.philsysIdNo?.trim() || null,
    sss_no: d.sssNo?.trim() || null,
    tin_no: d.tinNo?.trim() || null,
    philhealth_no: d.philhealthNo?.trim() || null,
    pagibig_no: d.pagibigNo?.trim() || null,
    passport_no: d.passportNo?.trim() || null,
    drivers_license_no: d.driversLicenseNo?.trim() || null,
    postal_id_no: d.postalIdNo?.trim() || null,
    // Emergency
    emergency_contact_name: d.emergencyContactName?.trim() || null,
    emergency_contact_relationship: d.emergencyContactRelationship?.trim() || null,
    emergency_contact_number: d.emergencyContactNumber?.trim() || null,
    // Status
    status: d.status || 'Active',
  };
}